function onOpen() {
  const ui = SpreadsheetApp.getUi()
  ui.createMenu('OPS Properties')
    .addItem('Set OPS Properties', 'setOpsProperties')
    .addItem('View Current OPS Properties', 'viewOpsProperties')
    .addItem('Clear OPS Properties', 'clearOpsProperties')
    .addToUi()
  const userMenu = ui.createMenu("Users")
    .addItem("Get Users", "DisplayUserFilterBuilder")
    .addItem("Create Users", "CreateUsers")
    .addItem("Update Users", "UpdateUsers")
  const employeeMenu = ui.createMenu("Employees")
    .addItem("Get Employees", "DisplayEmployeeFilterBuilder")
    .addItem("Create Employees", "CreateEmployees")
    .addItem("Update Employees", "UpdateEmployees")
  const equipmentMenu = ui.createMenu("Equipment")
    .addItem("Get Equipment", "DisplayEquipmentFilterBuilder")
    .addItem("Create Equipment", "CreateEquipment")
    .addItem("Update Equipment", "UpdateEquipment")
  const materialMenu = ui.createMenu("Materials")
    .addItem("Get Materials", "DisplayMaterialsFilterBuilder")
    .addItem("Create Materials", "CreateMaterials")
    .addItem("Update Materials", "UpdateMaterials")
  ui.createMenu('Run Scripts')
    .addSubMenu(userMenu)
    .addSubMenu(employeeMenu)
    .addSubMenu(equipmentMenu)
    .addSubMenu(materialMenu)
    .addToUi()

}